version: '3.8'

services:
  php:
    build:
      context: ./
      dockerfile: docker/php-fpm/Dockerfile
    container_name: symfony_php
    volumes:
      - .:/var/www/symfony
    networks:
      - symfony_network

  mysql:
    image: mysql:8.0
    container_name: symfony_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony_network

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/symfony
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge

volumes:
  mysql_data:
