services:
  php:
    container_name: task-tracker_php
    build:
      context: ./docker/php-fpm
    volumes:
      - .:/var/www/symfony
    working_dir: /var/www/symfony
    depends_on:
      - mysql

  mysql:
    container_name: task-tracker_mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    container_name: task-tracker_nginx
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./symfony:/var/www/symfony
      - ./docker/nginx/http.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  mysql_data:
